version: '3'
services:
  nginx:
    build: docker/nginx
    container_name: nginx-debug
    ports:
      - 80:80
    networks:
      - app-network
    volumes:
      - ./src:/var/www/app
    
  php:
    build: 
      dockerfile: docker/php8.1.6/Dockerfile
      context: ./
    container_name: php-debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    volumes:
      - ./src:/var/www/app
    expose:
      - 9000
    networks:
      - app-network
    depends_on:
      - "db"

networks:
  app-network:
    driver: bridge