version: '3'
services:
  nginx:
    build: docker/nginx
    container_name: nginx-debug-3.2
    ports:
      - 80:80
    networks:
      - app-network
    volumes:
      - ./src:/var/www/app
  php:
    build: 
      dockerfile: docker/php8.3.2/Dockerfile
      context: ./
    container_name: php-debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    volumes:
      - ./src:/var/www/app
    expose:
      - 9000
    networks:
      - app-network
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    container_name: mongodbServer
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
    ports:
        - 27017:27017
networks:
  app-network:
    driver: bridge